-- rollback for apply-alert-event-prefix.php on pid 271, generated 2026-09-21 15:46:25
UPDATE redcap_alerts SET `alert_condition` = '([event-name]=\'day_1_ed_arm_2\' or [event-name]=\'day_1_ed_arm_3\') and [randomization_date]<>\'\' and [mica_ed_session_complete]<>\'2\' and [email]<>\'\' and ([choice_fup_delivery(1)]=\'1\' and [choice_fup_delivery(2)]<>\'1\') and [study_withdrawn(1)]<>\'1\'' WHERE alert_id = 5750;  -- 02
UPDATE redcap_alerts SET `email_to` = '[email]' WHERE alert_id = 5750;  -- 02
UPDATE redcap_alerts SET `cron_send_email_on_field` = '[randomization_date]' WHERE alert_id = 5750;  -- 02
UPDATE redcap_alerts SET `alert_message` = '<p>Hi [first_name],</p><p>Your MICA session is ready and takes about 20 minutes.</p><p>[survey-link:mica_ed_session:Open your MICA session]</p><p>If you have questions, reply to this email.</p><p>— The MICA Study Team</p>' WHERE alert_id = 5750;  -- 02
UPDATE redcap_alerts SET `alert_condition` = '([event-name]=\'day_1_ed_arm_2\' or [event-name]=\'day_1_ed_arm_3\') and [randomization_date]<>\'\' and [mica_ed_session_complete]<>\'2\' and [phonen]<>\'\' and ([choice_fup_delivery(2)]=\'1\' or ([choice_fup_delivery(1)]<>\'1\' and [choice_fup_delivery(2)]<>\'1\')) and [study_withdrawn(1)]<>\'1\' and [sms_stop(1)]<>\'1\'' WHERE alert_id = 5751;  -- 03
UPDATE redcap_alerts SET `phone_number_to` = '[phonen]' WHERE alert_id = 5751;  -- 03
UPDATE redcap_alerts SET `cron_send_email_on_field` = '[randomization_date]' WHERE alert_id = 5751;  -- 03
UPDATE redcap_alerts SET `alert_message` = 'Hi [first_name], it\'s the MICA Team. Your MICA session is ready (about 20 min): [survey-url:mica_ed_session] Reply STOP to opt out.' WHERE alert_id = 5751;  -- 03
UPDATE redcap_alerts SET `alert_condition` = '([event-name]=\'day_1_ed_arm_2\' or [event-name]=\'day_1_ed_arm_3\') and [randomization_date]<>\'\' and [mica_ed_session_complete]<>\'2\' and [study_withdrawn(1)]<>\'1\'' WHERE alert_id = 5752;  -- 04
UPDATE redcap_alerts SET `cron_send_email_on_field` = '[randomization_date]' WHERE alert_id = 5752;  -- 04
UPDATE redcap_alerts SET `alert_message` = '<p>[form-link:admin:Open record [record-name] in REDCap]</p><p>Study group: [study_group] · Randomized: [randomization_date]</p><ul><li>The participant has not completed the MICA ED session 14 days after randomization.</li><li>An automated reminder was sent on day 7.</li><li><b>Action: phone the participant.</b> Contact: [phonen] / [email]</li></ul>' WHERE alert_id = 5752;  -- 04
UPDATE redcap_alerts SET `alert_condition` = '[event-name]=\'month_3_arm_2\' and [mica_booster_session_complete]<>\'2\' and [day_1_ed_arm_2][randomization_date]<>\'\' and [day_1_ed_arm_2][email]<>\'\' and ([day_1_ed_arm_2][choice_fup_delivery(1)]=\'1\' and [day_1_ed_arm_2][choice_fup_delivery(2)]<>\'1\') and [day_1_ed_arm_2][study_withdrawn(1)]<>\'1\'' WHERE alert_id = 5753;  -- 05
UPDATE redcap_alerts SET `email_to` = '[day_1_ed_arm_2][email]' WHERE alert_id = 5753;  -- 05
UPDATE redcap_alerts SET `cron_send_email_on_field` = '[day_1_ed_arm_2][randomization_date]' WHERE alert_id = 5753;  -- 05
UPDATE redcap_alerts SET `alert_message` = '<p>Hi [day_1_ed_arm_2][first_name],</p><p>It\'s time for your 3-month MICA booster session.</p><p>[survey-link:mica_booster_session:Open your booster session]</p><p>— The MICA Study Team</p>' WHERE alert_id = 5753;  -- 05
UPDATE redcap_alerts SET `alert_condition` = '[event-name]=\'month_3_arm_2\' and [mica_booster_session_complete]<>\'2\' and [day_1_ed_arm_2][randomization_date]<>\'\' and [day_1_ed_arm_2][phonen]<>\'\' and ([day_1_ed_arm_2][choice_fup_delivery(2)]=\'1\' or ([day_1_ed_arm_2][choice_fup_delivery(1)]<>\'1\' and [day_1_ed_arm_2][choice_fup_delivery(2)]<>\'1\')) and [day_1_ed_arm_2][study_withdrawn(1)]<>\'1\' and [day_1_ed_arm_2][sms_stop(1)]<>\'1\'' WHERE alert_id = 5754;  -- 06
UPDATE redcap_alerts SET `phone_number_to` = '[day_1_ed_arm_2][phonen]' WHERE alert_id = 5754;  -- 06
UPDATE redcap_alerts SET `cron_send_email_on_field` = '[day_1_ed_arm_2][randomization_date]' WHERE alert_id = 5754;  -- 06
UPDATE redcap_alerts SET `alert_message` = 'Hi [day_1_ed_arm_2][first_name], it\'s the MICA Team. Your 3-month booster session is ready: [survey-url:mica_booster_session] Reply STOP to opt out.' WHERE alert_id = 5754;  -- 06
UPDATE redcap_alerts SET `alert_condition` = '[event-name]=\'month_3_arm_2\' and [mica_booster_session_complete]<>\'2\' and [day_1_ed_arm_2][randomization_date]<>\'\' and [day_1_ed_arm_2][email]<>\'\' and ([day_1_ed_arm_2][choice_fup_delivery(1)]=\'1\' and [day_1_ed_arm_2][choice_fup_delivery(2)]<>\'1\') and [day_1_ed_arm_2][study_withdrawn(1)]<>\'1\'' WHERE alert_id = 5755;  -- 07
UPDATE redcap_alerts SET `email_to` = '[day_1_ed_arm_2][email]' WHERE alert_id = 5755;  -- 07
UPDATE redcap_alerts SET `cron_send_email_on_field` = '[day_1_ed_arm_2][randomization_date]' WHERE alert_id = 5755;  -- 07
UPDATE redcap_alerts SET `alert_message` = '<p>Hi [day_1_ed_arm_2][first_name],</p><p>It\'s time for your 3-month MICA booster session.</p><p>[survey-link:mica_booster_session:Open your booster session]</p><p>— The MICA Study Team</p>' WHERE alert_id = 5755;  -- 07
UPDATE redcap_alerts SET `alert_condition` = '[event-name]=\'month_3_arm_2\' and [mica_booster_session_complete]<>\'2\' and [day_1_ed_arm_2][randomization_date]<>\'\' and [day_1_ed_arm_2][phonen]<>\'\' and ([day_1_ed_arm_2][choice_fup_delivery(2)]=\'1\' or ([day_1_ed_arm_2][choice_fup_delivery(1)]<>\'1\' and [day_1_ed_arm_2][choice_fup_delivery(2)]<>\'1\')) and [day_1_ed_arm_2][study_withdrawn(1)]<>\'1\' and [day_1_ed_arm_2][sms_stop(1)]<>\'1\'' WHERE alert_id = 5756;  -- 08
UPDATE redcap_alerts SET `phone_number_to` = '[day_1_ed_arm_2][phonen]' WHERE alert_id = 5756;  -- 08
UPDATE redcap_alerts SET `cron_send_email_on_field` = '[day_1_ed_arm_2][randomization_date]' WHERE alert_id = 5756;  -- 08
UPDATE redcap_alerts SET `alert_message` = 'Hi [day_1_ed_arm_2][first_name], it\'s the MICA Team. Your 3-month booster session is ready: [survey-url:mica_booster_session] Reply STOP to opt out.' WHERE alert_id = 5756;  -- 08
UPDATE redcap_alerts SET `alert_condition` = '[event-name]=\'month_3_arm_2\' and [mica_booster_session_complete]<>\'2\' and [day_1_ed_arm_2][randomization_date]<>\'\' and [day_1_ed_arm_2][study_withdrawn(1)]<>\'1\'' WHERE alert_id = 5757;  -- 09
UPDATE redcap_alerts SET `cron_send_email_on_field` = '[day_1_ed_arm_2][randomization_date]' WHERE alert_id = 5757;  -- 09
UPDATE redcap_alerts SET `alert_message` = '<p>[form-link:close:Open record [record-name] in REDCap]</p><p>Study group: [day_1_ed_arm_2][study_group] · Randomized: [day_1_ed_arm_2][randomization_date]</p><ul><li>The participant has not completed the MICA booster session, now 14 days past the Month 3 target.</li><li>Automated reminders were sent on day 92 and day 98.</li><li><b>Action: phone the participant.</b> Contact: [day_1_ed_arm_2][phonen] / [day_1_ed_arm_2][email]</li></ul>' WHERE alert_id = 5757;  -- 09
UPDATE redcap_alerts SET `alert_condition` = '[event-name]=\'month_3_arm_3\' and [mica_booster_session_complete]<>\'2\' and [day_1_ed_arm_3][randomization_date]<>\'\' and [day_1_ed_arm_3][email]<>\'\' and ([day_1_ed_arm_3][choice_fup_delivery(1)]=\'1\' and [day_1_ed_arm_3][choice_fup_delivery(2)]<>\'1\') and [day_1_ed_arm_3][study_withdrawn(1)]<>\'1\'' WHERE alert_id = 5758;  -- 10
UPDATE redcap_alerts SET `email_to` = '[day_1_ed_arm_3][email]' WHERE alert_id = 5758;  -- 10
UPDATE redcap_alerts SET `cron_send_email_on_field` = '[day_1_ed_arm_3][randomization_date]' WHERE alert_id = 5758;  -- 10
UPDATE redcap_alerts SET `alert_message` = '<p>Hi [day_1_ed_arm_3][first_name],</p><p>It\'s time for your 3-month MICA booster session.</p><p>[survey-link:mica_booster_session:Open your booster session]</p><p>— The MICA Study Team</p>' WHERE alert_id = 5758;  -- 10
UPDATE redcap_alerts SET `phone_number_to` = '[day_1_ed_arm_3][phonen]' WHERE alert_id = 5759;  -- 11
UPDATE redcap_alerts SET `cron_send_email_on_field` = '[day_1_ed_arm_3][randomization_date]' WHERE alert_id = 5759;  -- 11
UPDATE redcap_alerts SET `alert_message` = '<p>Hi [day_1_ed_arm_3][first_name], it\'s the MICA Team. Your 3-month booster session is ready: [survey-url:mica_booster_session] Reply STOP to opt out.</p>' WHERE alert_id = 5759;  -- 11
UPDATE redcap_alerts SET `alert_condition` = '[event-name]=\'month_3_arm_3\' and [mica_booster_session_complete]<>\'2\' and [day_1_ed_arm_3][randomization_date]<>\'\' and [day_1_ed_arm_3][email]<>\'\' and ([day_1_ed_arm_3][choice_fup_delivery(1)]=\'1\' and [day_1_ed_arm_3][choice_fup_delivery(2)]<>\'1\') and [day_1_ed_arm_3][study_withdrawn(1)]<>\'1\'' WHERE alert_id = 5760;  -- 12
UPDATE redcap_alerts SET `email_to` = '[day_1_ed_arm_3][email]' WHERE alert_id = 5760;  -- 12
UPDATE redcap_alerts SET `cron_send_email_on_field` = '[day_1_ed_arm_3][randomization_date]' WHERE alert_id = 5760;  -- 12
UPDATE redcap_alerts SET `alert_message` = '<p>Hi [day_1_ed_arm_3][first_name],</p><p>It\'s time for your 3-month MICA booster session.</p><p>[survey-link:mica_booster_session:Open your booster session]</p><p>— The MICA Study Team</p>' WHERE alert_id = 5760;  -- 12
UPDATE redcap_alerts SET `alert_condition` = '[event-name]=\'month_3_arm_3\' and [mica_booster_session_complete]<>\'2\' and [day_1_ed_arm_3][randomization_date]<>\'\' and [day_1_ed_arm_3][phonen]<>\'\' and ([day_1_ed_arm_3][choice_fup_delivery(2)]=\'1\' or ([day_1_ed_arm_3][choice_fup_delivery(1)]<>\'1\' and [day_1_ed_arm_3][choice_fup_delivery(2)]<>\'1\')) and [day_1_ed_arm_3][study_withdrawn(1)]<>\'1\' and [day_1_ed_arm_3][sms_stop(1)]<>\'1\'' WHERE alert_id = 5761;  -- 13
UPDATE redcap_alerts SET `phone_number_to` = '[day_1_ed_arm_3][phonen]' WHERE alert_id = 5761;  -- 13
UPDATE redcap_alerts SET `cron_send_email_on_field` = '[day_1_ed_arm_3][randomization_date]' WHERE alert_id = 5761;  -- 13
UPDATE redcap_alerts SET `alert_message` = 'Hi [day_1_ed_arm_3][first_name], it\'s the MICA Team. Your 3-month booster session is ready: [survey-url:mica_booster_session] Reply STOP to opt out.' WHERE alert_id = 5761;  -- 13
UPDATE redcap_alerts SET `alert_condition` = '[event-name]=\'month_3_arm_3\' and [mica_booster_session_complete]<>\'2\' and [day_1_ed_arm_3][randomization_date]<>\'\' and [day_1_ed_arm_3][study_withdrawn(1)]<>\'1\'' WHERE alert_id = 5762;  -- 14
UPDATE redcap_alerts SET `cron_send_email_on_field` = '[day_1_ed_arm_3][randomization_date]' WHERE alert_id = 5762;  -- 14
UPDATE redcap_alerts SET `alert_message` = '<p>[form-link:close:Open record [record-name] in REDCap]</p><p>Study group: [day_1_ed_arm_3][study_group] · Randomized: [day_1_ed_arm_3][randomization_date]</p><ul><li>The participant has not completed the MICA booster session, now 14 days past the Month 3 target.</li><li>Automated reminders were sent on day 92 and day 98.</li><li><b>Action: phone the participant.</b> Contact: [day_1_ed_arm_3][phonen] / [day_1_ed_arm_3][email]</li></ul>' WHERE alert_id = 5762;  -- 14
